version: '3.0.{build}'
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '3.0.{build}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

configuration: Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

build:
  publish_nuget: true
  publish_nuget_symbols: false

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

before_build:
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build src\AwesomeSockets.**\project.json -c %CONFIGURATION%

after_build:
- dotnet pack src\AwesomeSockets.Interfaces -c %CONFIGURATION% --no-build -o artifacts
- dotnet pack src\AwesomeSockets.Core -c %CONFIGURATION% --no-build -o artifacts
- dotnet pack src\AwesomeSockets.Routing -c %CONFIGURATION% --no-build -o artifacts
- dotnet pack src\AwesomeSockets.Reactive.Additions -c %CONFIGURATION% --no-build -o artifacts

#test_script:
#- dotnet test "test\AwesomeSockets.Tests" -c %CONFIGURATION%
#- dotnet test "test\AwesomeSockets.Acceptance.Tests" -c %CONFIGURATION%

artifacts:
- path: artifacts\**\*.*

# TODO: Re-add just before releasing...
#deploy:
#  provider: NuGet
#  api_key:
#    secure: YYJVXyOvCQ0+eH0+nYybXRh3lxCdCXBcMMduj+YzdPmJWASjKMlkdu72BvW4Xksu
#  skip_symbols: true
